layout_spectrum: 0.26114
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.1935484
  lightness: 0.25
  brandColors:
    - '#0d0906'
    - '#ca8937'
    - '#622006'
    - '#a36f3d'
    - '#4e3e2f'
  rhythmicContrast: 0.5
typography_spectrum: 0.8602151
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: STUDIO NOIR
