name: STUDIO NOIR
favicon: null
layout_spectrum: 0.26114
typography_spectrum: 0.67237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0906'
    - '#ca8937'
    - '#622006'
    - '#a36f3d'
    - '#4e3e2f'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
